In [1]:
import numpy as np

In [5]:
X = np.array([

[2.5, 2.4, 2.7],

[0.5, 0.7, 3.6],

[2.2, 2.9, 4.2],

[1.9, 2.2, 5.5],

[3.1, 3.0, 2.3]

])

# Step 2: Mean centering

X_meaned = X - np.mean(X, axis=0)

# Step 3: Covariance matrix

cov_matrix = np.cov(X_meaned, rowvar=False)

# Step 4: Eigen decomposition

eigen_values, eigen_vectors = np.linalg.eig(cov_matrix)

# Step 5: Sort eigenvalues and eigenvectors

sorted_index = np.argsort(eigen_values)[::-1]

sorted_eigenvalues = eigen_values[sorted_index]

sorted_eigenvectors = eigen_vectors[:, sorted_index]

# Step 6: Select top k eigenvectors (k=1 or 2)

k = 2

eigenvector_subset = sorted_eigenvectors[:, :k]

# Step 7: Transform the data

X_reduced = np.dot(X_meaned, eigenvector_subset)

# Output results

print("Covariance Matrix:\n", cov_matrix)

print("\nEigen Values:\n", eigen_values)

print("\nPrincipal Component (Top Eigenvector):\n", eigenvector_subset)

print("\nData after PCA (1D):\n", X_reduced)

Covariance Matrix:
 [[ 0.938   0.8405 -0.4905]
 [ 0.8405  0.853  -0.203 ]
 [-0.4905 -0.203   1.613 ]]

Eigen Values:
 [0.02864673 2.18183021 1.19352307]

Principal Component (Top Eigenvector):
 [[-0.57951705  0.39983675]
 [-0.46842827  0.54962199]
 [ 0.66688451  0.73351635]]

Data after PCA (1D):
 [[-0.98173549 -0.43231128]
 [ 1.57382272 -1.50617744]
 [-0.04176775  0.82282323]
 [ 1.32693701  1.27170807]
 [-1.87725649 -0.15604257]]


In [ ]:
Covariance Matrix:
 [[0.61655556 0.61544444]
 [0.61544444 0.71655556]]

Eigen Values:
 [0.0490834  1.28402771]

Principal Component (Top Eigenvector):
 [[-0.6778734 ]
 [-0.73517866]]

Data after PCA (1D):
 [[-0.82797019]
 [ 1.77758033]
 [-0.99219749]
 [-0.27421042]
 [-1.67580142]
 [-0.9129491 ]
 [ 0.09910944]
 [ 1.14457216]
 [ 0.43804614]
 [ 1.22382056]]